driver:
  name: vagrant

driver_config:
  customize:
    memory: 1024  
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[df_ntp::default]
    attributes:
